# Generated by Django 5.2.8 on 2025-11-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The human-readable name of the election.', max_length=255, unique=True)),
                ('election_id', models.SlugField(blank=True, help_text='A unique ID for use in URLs.', max_length=255, unique=True)),
                ('positions_json', models.JSONField(help_text='JSON object defining positions and their candidates.')),
                ('is_active', models.BooleanField(default=False, help_text='Marks if this election is open for voting.')),
            ],
        ),
        migrations.CreateModel(
            name='VoteLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_data', models.JSONField()),
                ('timestamp', models.DateTimeField(db_index=True, editable=False)),
                ('previous_hash', models.CharField(blank=True, help_text="Hash of the previous block/vote in this election's chain.", max_length=64)),
                ('current_hash', models.CharField(db_index=True, help_text="Hash of this vote's data.", max_length=64, unique=True)),
                ('election', models.ForeignKey(help_text='The election this vote belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='voting_api.election')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_hash', models.CharField(db_index=True, max_length=64)),
                ('has_voted', models.BooleanField(default=False, help_text="Set to True when this person's ballot is cast.")),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voting_api.election')),
            ],
            options={
                'unique_together': {('election', 'voter_hash')},
            },
        ),
    ]
