# Generated by Django 5.2.8 on 2025-11-16 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreApprovedVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', models.CharField(db_index=True, max_length=255)),
                ('is_linked', models.BooleanField(default=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preapproved_voters', to='voting_api.election')),
            ],
            options={
                'unique_together': {('election', 'unique_identifier')},
            },
        ),
    ]
